<?php
/** @var array $sliced_pages */
/** @var int $paged */
/** @var int $total */
/** @var string $base */

$total_pages = ceil($total / 50); // Optional, for pagination
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>XML Sitemap</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; background: #f5f5f5; color: #333; }
        .header { background: #3474f7; color: white; padding: 20px 40px; }
        .header h1 { margin: 0; font-size: 28px; font-weight: 600; }
        .header p { margin-top: 8px; font-size: 14px; color: rgba(255,255,255,0.9); }
        .header a { color: #ffffff; text-decoration: underline; }
        .container { padding: 30px 40px; }
        h2 { font-size: 18px; margin-bottom: 20px; }
        .sitemap-table { width: 100%; border-collapse: collapse; background: #fff; box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05); }
        .sitemap-table thead { background: #3474f7; color: white; }
        .sitemap-table th, .sitemap-table td { padding: 12px 16px; border-bottom: 1px solid #ddd; font-size: 14px; }
        .sitemap-table tr:nth-child(even) { background-color: #f9f9f9; }
        .sitemap-table a { color: #0073aa; text-decoration: none; }
        .sitemap-table a:hover { text-decoration: underline; }
        .sitemap-index-link { margin-bottom: 20px; display: inline-block; font-size: 15px; }
    </style>
</head>
<body>
<div class="header">
    <h1>XML Sitemap</h1>
    <p>This XML Sitemap is generated by a custom sitemap system. It helps search engines crawl your pages efficiently.<br>
        Learn more about <a href="https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview" target="_blank">XML Sitemaps</a>.</p>
</div>
<div class="container">
    <a class="sitemap-index-link" href="<?php echo esc_url($base . 'sitemap_index.xml'); ?>">&larr; Sitemap Index</a>
    <h2>This XML Sitemap contains <?php echo esc_html($total); ?> URLs.</h2>
    <table class="sitemap-table">
        <thead>
        <tr>
            <th>URL</th>
            <th>Last Mod.</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($sliced_pages as $page): ?>
            <tr>
                <td><a href="<?php echo esc_url(get_permalink($page)); ?>"><?php echo esc_url(get_permalink($page)); ?></a></td>
                <td><?php echo esc_html(get_the_modified_time('Y-m-d H:i +00:00', $page)); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
</body>
</html>
